import type { Metadata } from "next";
import Link from "next/link";
import { BrandLogo } from "@/components/brand-logo";

export const metadata: Metadata = { title: "Privacy Policy | Navill Tech", description: "How Navill Tech handles project enquiries and privacy-friendly website analytics." };

export default function PrivacyPage() {
  return <main><header className="nav-wrap"><nav className="nav container"><BrandLogo href="/" compact/><Link className="btn btn-small" href="/">Back to website</Link></nav></header><section className="section"><article className="container" style={{maxWidth:820,paddingTop:80}}><div className="section-heading"><span className="kicker">PRIVACY POLICY</span><h1>Your information stays <span className="gradient-text">private.</span></h1><p>Last updated 15 August 2026</p></div><div style={{display:"grid",gap:28,color:"#aeb8c5",lineHeight:1.8}}><section><h2 style={{color:"white",marginBottom:8}}>Project enquiries</h2><p>When you submit an enquiry, Navill Tech stores the contact and project information you provide so Victor can review and respond to your request. This information is not sold or used for advertising.</p></section><section><h2 style={{color:"white",marginBottom:8}}>Website analytics</h2><p>The website records privacy-friendly events such as page views and button clicks, together with general device, browser, referrer and country information. Raw IP addresses and advertising profiles are not stored. Anonymous analytics events are retained for up to 12 months.</p></section><section><h2 style={{color:"white",marginBottom:8}}>Service providers</h2><p>Supabase hosts enquiry and analytics data. Twilio and Gmail may process notification messages. Vercel hosts the website and supplies approximate country headers. These providers process information only to operate the website and enquiry workflow.</p></section><section><h2 style={{color:"white",marginBottom:8}}>Retention and your choices</h2><p>Enquiries remain available until they are no longer needed or are manually deleted. You may ask to access, correct or delete your enquiry by emailing <a className="text-link" href="mailto:victoriyoyo2493@gmail.com">victoriyoyo2493@gmail.com</a>.</p></section></div></article></section></main>;
}
